import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>BDEMR Clinic App Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">BDEMR</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href={"/page-accounts"}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2> Discount &rarr;</h2>
            </a>
          </Link>
          <Link href={"/due-page"}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Due report &rarr;</h2>
            </a>
          </Link>
          <Link href={"/addmissionPage"}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2> Addmission &rarr;</h2>
            </a>
          </Link>
          <Link href={"/operationNote"}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Dooctor note &rarr;</h2>
            </a>
          </Link>
          <Link href="preOperation">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Pre Operation &rarr;</h2>
            </a>
          </Link>
          <Link href="PostOperation">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Post Operation &rarr;</h2>
            </a>
          </Link>
          <Link href="madicationPage">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Madication chart &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
